project:
  name: tinydft
  conda_requirements: [numpy, scipy, autograd, matplotlib]
  packages:
    - dist_name: tinydft
      tools:
        - cardboardlint-static
        - upload-codecov
        - pytest
        - test-main

tools:
  pytest:
    commands:
      - pytest -v --cov=tinydft --cov=tinygrid
          --cov-report xml:coverage_pytest.xml
          --cov-report term-missing
          --cov-branch --color=yes
          -n auto

  test-main:
    task: test-inplace
    conda_requirements:
      - coverage
    commands:
      - >
        export MATPLOTLIBRC=$PWD;
        echo "backend: agg" > $MATPLOTLIBRC/matplotlibrc;
        coverage run -m tinydft
      - coverage xml -i -o coverage_main.xml
